name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl "https://github-readme-stats.vercel.app/api/top-langs?username=theg1239&show_icons=true&locale=en&layout=compact&theme=dark&count_private=true&token=${GITHUB_TOKEN}" > stats.svg
          echo "![GitHub Stats](./stats.svg)" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md stats.svg
          git commit -m "Update GitHub stats [skip ci]"
          git push
