name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl "https://https://readme-stats-puce.vercel.app/api/top-langs?username=theg1239&show_icons=true&locale=en&layout=compact&theme=dark&count_private=true=${{ secrets.GH_STATS_TOKEN }}" > stats.svg

      - name: Update README
        run: |
          sed -i 's|!\[GitHub Stats\](.*)|![GitHub Stats](./stats.svg)|g' README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md stats.svg
          git commit -m "Update GitHub stats [skip ci]" || exit 0
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/theg1239/theg1239.git" HEAD:main
